---
driver:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  require_chef_for_busser: true

platforms:
  - name: ubuntu1404
    driver_config:
      image: ubuntu:14.04
      socket: <%= ENV['DOCKER_HOST'] %>
      use_cache: true
      dockerfile: ubuntu14.04-dockerfile
  - name: ubuntu1410
    driver_config:
      image: ubuntu:14.10
      socket: <%= ENV['DOCKER_HOST'] %>
      use_cache: true
      dockerfile: ubuntu14.10-dockerfile
  - name: debian7
    driver_config:
      image: debian:7.7
      socket: <%= ENV['DOCKER_HOST'] %>
      use_cache: true
      dockerfile: debian7.7-dockerfile
suites:
  - name: webserver
    provisioner:
      manifest: site.pp
